accounts/urls.py
from django.urls import path
from accounts.views import CreateUser, LoginUser, LogoutUser

app_name = "accounts"

urlpatterns = [
    path("register/", CreateUser.as_view(), name="Register"),
    path("login/", LoginUser.as_view(), name="Login"),
    path("logout/", LogoutUser.as_view(), name="Logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storage.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import TextInput, CheckboxInput


class CreateNewUserForm(UserCreationForm):
    password1 = forms.CharField(label=("Senha"), strip=False,
                                widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),)

    password2 = forms.CharField(label=("Confirmar Senha"), strip=False,
                                widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),)

    class Meta:
        model = User

        fields = ["username", "password1", "password2", "is_superuser"]
        widgets = {
            "username": TextInput(attrs={"class": "form-control"}),
        }
        error_messages = {
            "username": {
                "required": "O nome de usuário é obrigatório.",
                "unique": "Este nome de usuário já está em uso.",
                "max_length": "O nome de usuário não pode exceder 150 caracteres.",
            },
            "password1": {
                "required": "Você precisa informar uma senha.",
                "min_length": "A senha deve ter pelo menos 8 caracteres.",
            },
            "password2": {
                "required": "Você precisa confirmar a senha.",
                "password_mismatch": "As senhas não coincidem.",
            },
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["is_superuser"].widget = CheckboxInput(attrs={"class": "form-check-input"})
        self.fields["is_superuser"].label = "Super Usuário"
        self.fields["is_superuser"].required = False


class LoginUserForm(AuthenticationForm):
    error_messages = {
        "invalid_login": "Credenciais inválidas. Por favor, tente novamente.",
        "inactive": "Esta conta está inativa.",
    }

    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Usuário"}),
        label=("Usuário"),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Senha"}),
        label=("Senha"),
    )

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from accounts.forms import CreateNewUserForm, LoginUserForm


class CreateUser(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = User
    form_class = CreateNewUserForm
    template_name = "register_template.html"
    context_object_name = "form"
    success_url = reverse_lazy("storage:Home")

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect("storage:Home")

    def form_valid(self, form):
        new_user = form.save(commit=False)
        if form.cleaned_data["is_superuser"]:
            new_user.is_superuser = True
            new_user.is_staff = True
        new_user.save()
        return super().form_valid(form)


class LoginUser(LoginView):
    form_class = LoginUserForm
    context_object_name = "form"
    template_name = "login_template.html"
    success_url = reverse_lazy("storage:Home")

    def get_success_url(self):
        return self.success_url


class LogoutUser(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy("accounts:Login")

accounts/templates/create.html
{% extends 'starter.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid mx-auto my-4 bg-light text-center rounded-pill border border-dark" style="max-width: 600px;">
        <h1 class="p-1">{{form_title}}</h1>
    </div>

    <div class="container-fluid mx-auto border border-2 rounded p-4" style="max-width: 550px;">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    {{field.label}}
                    {{field}}
                </div>
            {% endfor %}
            <input type="submit" value="{{form_btn_success}}" class="mt-3 btn btn-lg btn-success mx-auto d-flex p-2">
        </form>
    </div>

    <div class="container-fluid mx-auto my-4 text-center">
        <a href="{% url retrieve %}" class="btn btn-outline-primary w-25 p-2" style="max-width: 400px;">Voltar ao inicio</a>
    </div>
{% endblock %}

accounts/templates/form_acc.html
{% extends 'starter.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid mx-auto my-4 bg-light text-center rounded-pill border border-dark" style="max-width: 600px;">
        <h1 class="p-1">{{form_title}}</h1>
    </div>

    <div class="container-fluid mx-auto border border-2 rounded p-4 bg-light" style="max-width: 550px;">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    {{field.label}}
                    {{field}}
                    <div class="text-danger">
                        {{field.errors}}
                        {% if form.non_field_errors %}
                            {{ form.non_field_errors|striptags }}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <input type="submit" value="{{form_btn_success}}" class="mt-3 btn btn-lg btn-success mx-auto d-flex p-2">
        </form>
    </div>

    <div class="container-fluid mx-auto my-4 text-center">
        <a href="{% url retrieve %}" class="btn btn-primary w-50 p-2" style="max-width: 400px;">Voltar ao inicio</a>
    </div>
{% endblock %}

accounts/templates/login_template.html
{% extends 'starter.html' %}
{% load static %}

{% block title %}Faça Login Para Acessar o sistema {% endblock %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block content %}
    

    <div class="container-sm mx-auto border border-2 rounded-3 my-5 p-4 bg-light my-container">
        <h1 class="h1 text-center my-3">Realizar Login</h1>
        <hr>
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="row w-75 mx-auto my-input">
                <span class="fs-5 fw-semibold text-center mb-1">{{form.username.label}}</span>
                <div class="input-group mb-3">
                    <span class="input-group-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        </svg>
                    </span>
                    {{form.username}}
                </div>
            </div>
            <div class="row w-75 mx-auto my-input">
                <span class="fs-5 fw-semibold text-center mb-1">{{form.password.label}}</span>
                <div class="input-group mb-3">
                    <span class="input-group-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                            <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2M2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
                          </svg>
                    </span>
                    {{form.password}}
                </div>
            </div>
            <div class="row w-175 mx-auto my-input">
                {% if form.non_field_errors %}
                    <span class="fw-5 text-danger fw-semibold">{{ form.non_field_errors|striptags }}</span>
                {% endif %}
            </div>
            <input type="submit" value="Acessar o Sistema" class="mt-4 btn btn-lg btn-success mx-auto d-flex p-2">
        </form>
    </div>
{% endblock %}

accounts/templates/register_template.html
{% extends 'starter.html' %}
{% load static %}

{% block title %}Cadastrar Novo Funcionario{% endblock %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block content %}

    <div class="container-fluid mx-auto border border-2 mt-5 rounded p-4 bg-light my-container">
        <div class="d-flex flex-row justify-content-between mb-2">
            <p class="h1 text-center my-2 title">Registrar Vendedor</p>
            <p class="p-1 h1 me-2">
                <a href="{% url 'storage:Home' %}" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"/>
                        <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                      </svg>
                </a>
            </p>
        </div>
        <hr class="mb-4">

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="row w-75 mx-auto my-input">
                <span class="fs-5 fw-semibold text-center mb-1">{{form.username.label}}</span>
                <div class="input-group mb-3">
                    <span class="input-group-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        </svg>
                    </span>
                    {{form.username}}
                </div>
            </div>
            <div class="row w-75 mx-auto my-input">
                <span class="fs-5 fw-semibold text-center mb-1">{{form.password1.label}}</span>
                <div class="input-group mb-3">
                    <span class="input-group-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                            <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2M2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
                          </svg>
                    </span>
                    {{form.password1}}
                </div>
            </div>
            <div class="row w-75 mx-auto my-input">
                <span class="fs-5 fw-semibold text-center mb-1">{{form.password2.label}}</span>
                <div class="input-group mb-3">
                    <span class="input-group-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                            <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2M2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
                          </svg>
                    </span>
                    {{form.password2}}
                </div>
            </div>
            <div class="row w-75 mx-auto my-input">
                <div class="form-check form-switch mx-5">
                    <input class="form-check-input" type="checkbox" id="is_superuser" name="is_superuser">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Administrador do sistema</label>
                </div>
            </div>
            <div class="row w-75 mx-auto my-input">
                <span class="text-center fw-semibold text-danger">{{form.username.errors}}</span>
                <span class="text-center fw-semibold text-danger">{{form.password1.errors}}</span>
                <span class="text-center fw-semibold text-danger">{{form.password2.errors}}</span>
            </div>
            <input type="submit" value="Adicionar Novo Vendedor" class="mt-3 btn btn-lg btn-success mx-auto d-flex p-2">
        </form>
    </div>

{% endblock %}

core/templates/starter.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/starter.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block settings %} {% endblock %}
</head>
<body>
    <header class="bg-dark">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark mx-auto">
            <div class="container-fluid">
                
                {% if user.is_authenticated %}
                    <h1 class="navbar-brand fs-2 ms-3 title">Pet's Food - {{user.username}}</h1>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_navbar" aria-controls="main_navbar" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse d-lg-flex justify-content-end me-4" id="main_navbar">
                        <ul class="navbar-nav ms-5">
                            {% if user.is_authenticated %}
                            <li class="nav-item mx-2 fs-5"><a href="{% url 'storage:Home' %}" class="nav-link">Estoque</a></li>
                            {% if user.is_superuser %}
                                <li class="nav-item dropdown mx-2">
                                    <a role="button" data-bs-toggle="dropdown" aria-expanded="false" href="" class="nav-link dropdown-toggle fs-5">Adminstração</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{% url 'storage:Create' %}" class="dropdown-item">Nova Ração
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg text-success ms-2" viewBox="0 0 16 16">
                                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                                                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                                                </svg>
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="{% url 'storage:CreateBrand' %}" class="dropdown-item">Nova Marca
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg text-success ms-2" viewBox="0 0 16 16">
                                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                                                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                                                </svg>
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="{% url 'accounts:Register' %}" class="dropdown-item">Registrar Vendedor 
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill text-success ms-2" viewBox="0 0 16 16">
                                                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                                                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
                                            </svg>
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="{% url 'storage:ShowTransition' %}" class="dropdown-item">Visualizar Transações
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock-history ms-2" viewBox="0 0 16 16">
                                                    <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022zm2.004.45a7 7 0 0 0-.985-.299l.219-.976q.576.129 1.126.342zm1.37.71a7 7 0 0 0-.439-.27l.493-.87a8 8 0 0 1 .979.654l-.615.789a7 7 0 0 0-.418-.302zm1.834 1.79a7 7 0 0 0-.653-.796l.724-.69q.406.429.747.91zm.744 1.352a7 7 0 0 0-.214-.468l.893-.45a8 8 0 0 1 .45 1.088l-.95.313a7 7 0 0 0-.179-.483m.53 2.507a7 7 0 0 0-.1-1.025l.985-.17q.1.58.116 1.17zm-.131 1.538q.05-.254.081-.51l.993.123a8 8 0 0 1-.23 1.155l-.964-.267q.069-.247.12-.501m-.952 2.379q.276-.436.486-.908l.914.405q-.24.54-.555 1.038zm-.964 1.205q.183-.183.35-.378l.758.653a8 8 0 0 1-.401.432z"/>
                                                    <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0z"/>
                                                    <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5"/>
                                                </svg>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="{% url 'storage:ShowRelatory' %}" class="dropdown-item">Realatorio semanal de vendas</a>
                                        </li>
    
                                        <li>
                                            <a href="{% url 'admin:index' %}" class="dropdown-item">Página Administrativa
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-award-fill text-primary ms-2" viewBox="0 0 16 16">
                                                    <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864z"/>
                                                    <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1z"/>
                                                </svg>
                                            </a>
                                        </li>
                            
                                    </ul>
                                </li>
    
                                <li class="nav-item mx-2 fs-5"><a href="{% url 'storage:AlertHome' %}" class="nav-link">Rações em Alerta</a></li>
                            {% endif %}
                            <li class="nav-item mx-2 fs-5">
                                <form action="{% url 'accounts:Logout' %}" method="post">{% csrf_token %}
                                    <button type="submit" class="nav-link">Logout
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right ms-1" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                        </svg>
                                    </button>
                                </form>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                {% else %}
                    <h1 class="navbar-brand fs-2 mx-auto title">Faça login para continuar</h1>
                {% endif %}
            </div>
        </nav>
    </header>
    
    <main class="container-fluid p-0 p-md-2">
        {% block content %}
        
        {% endblock %}
    </main>

    {% block js_settings %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>